Repository hanghae-plus-backend-8/prestudy-framework-spring, pull requests merged in 2025-03, with the labels that each got.

#17 [PR - 1주차 진문장] 게시글 CRUD 기능 구현
  assignments/week1/Q&A.md
  assignments/week1/api-docs.yaml
  src/main/java/com/hhplus/precourse/common/exception/CommonExceptionHandler.java
  src/main/java/com/hhplus/precourse/post/controller/CreatePostController.java
  src/main/java/com/hhplus/precourse/post/controller/DeletePostController.java
  src/main/java/com/hhplus/precourse/post/controller/GetPostController.java
  src/main/java/com/hhplus/precourse/post/controller/GetPostListController.java
  src/main/java/com/hhplus/precourse/post/controller/UpdatePostController.java
  src/main/java/com/hhplus/precourse/post/domain/Post.java
  src/main/java/com/hhplus/precourse/post/repository/PostRepository.java
  src/main/java/com/hhplus/precourse/post/service/CreatePostService.java
  src/main/java/com/hhplus/precourse/post/service/DeletePostService.java
  src/main/java/com/hhplus/precourse/post/service/GetPostListService.java
  src/main/java/com/hhplus/precourse/post/service/GetPostService.java
  src/main/java/com/hhplus/precourse/post/service/UpdatePostService.java
  src/main/java/com/hhplus/precourse/post/vo/PostVo.java
  src/main/resources/application-local.yml
  src/test/java/com/hhplus/board/PreCourseApplicationTests.java
  src/test/java/com/hhplus/precourse/common/ApiDocumentUtils.java
  src/test/java/com/hhplus/precourse/common/ControllerTestContext.java
  src/test/java/com/hhplus/precourse/common/FixtureReflectionUtils.java
  src/test/java/com/hhplus/precourse/common/TestFixture.java
  src/test/java/com/hhplus/precourse/post/controller/CreatePostControllerTest.java
  src/test/java/com/hhplus/precourse/post/controller/DeletePostControllerTest.java
  src/test/java/com/hhplus/precourse/post/controller/GetPostControllerTest.java
  src/test/java/com/hhplus/precourse/post/controller/GetPostListControllerTest.java
  src/test/java/com/hhplus/precourse/post/controller/UpdatePostControllerTest.java
  src/test/java/com/hhplus/precourse/post/domain/PostFixture.java
  src/test/java/com/hhplus/precourse/post/domain/PostTest.java
  src/test/java/com/hhplus/precourse/post/service/CreatePostServiceTest.java
  src/test/java/com/hhplus/precourse/post/service/DeletePostServiceTest.java
  src/test/java/com/hhplus/precourse/post/service/UpdatePostServiceTest.java
Labels: ✨ Feature

#14 [PR - 1주차 박한영] 도큐먼트 작성 및 게시물 CRUD 기능 구현
  .gitattributes
  .gitignore
  build.gradle
  docs/ApiDocument.md
  docs/ERD.md
  docs/UseCase.md
  docs/WIL/week1.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/prestudy/framework/spring/PrestudyFrameworkSpringApplication.java
  src/main/java/prestudy/framework/spring/api/config/SwaggerConfig.java
  src/main/java/prestudy/framework/spring/api/controller/board/BoardController.java
  src/main/java/prestudy/framework/spring/api/controller/board/request/BoardCreateRequest.java
  src/main/java/prestudy/framework/spring/api/controller/board/request/BoardDeleteRequest.java
  src/main/java/prestudy/framework/spring/api/controller/board/request/BoardUpdateRequest.java
  src/main/java/prestudy/framework/spring/api/controller/board/response/BoardResponse.java
  src/main/java/prestudy/framework/spring/api/controller/common/response/ApiResponse.java
  src/main/java/prestudy/framework/spring/api/exception/ApiExceptionHandler.java
  src/main/java/prestudy/framework/spring/api/service/board/BoardService.java
  src/main/java/prestudy/framework/spring/api/service/board/command/BoardCreateCommand.java
  src/main/java/prestudy/framework/spring/api/service/board/command/BoardDeleteCommand.java
  src/main/java/prestudy/framework/spring/api/service/board/command/BoardUpdateCommand.java
  src/main/java/prestudy/framework/spring/config/JpaAuditingConfig.java
  src/main/java/prestudy/framework/spring/domain/BaseEntity.java
  src/main/java/prestudy/framework/spring/domain/board/Board.java
  src/main/java/prestudy/framework/spring/domain/board/BoardRepository.java
  src/main/resources/application.yml
  src/test/java/prestudy/framework/spring/PrestudyFrameworkSpringApplicationTests.java
  src/test/java/prestudy/framework/spring/api/controller/board/BoardControllerTest.java
  src/test/java/prestudy/framework/spring/api/service/board/BoardServiceTest.java
  src/test/java/prestudy/framework/spring/domain/board/BoardRepositoryTest.java
  src/test/java/prestudy/framework/spring/domain/board/BoardTest.java
  src/test/java/prestudy/framework/spring/support/ControllerTestSupport.java
  src/test/java/prestudy/framework/spring/support/IntegrationTestSupport.java
Labels: ✨ Feature, 📝 Document

#18 [PR - 1주차 이건엽] 게시글 CRUD 기능 구현
  build.gradle
  src/main/generated/hanghaeboard/domain/member/QMember.java
  src/main/java/hanghaeboard/api/ApiResponse.java
  src/main/java/hanghaeboard/api/controller/user/UserController.java
  src/main/java/hanghaeboard/api/controller/user/request/CreateUserRequest.java
  src/main/java/hanghaeboard/api/controller/user/request/LoginRequest.java
  src/main/java/hanghaeboard/api/exception/ApiControllerAdvice.java
  src/main/java/hanghaeboard/api/service/member/MemberService.java
  src/main/java/hanghaeboard/api/service/member/response/FindMember.java
  src/main/java/hanghaeboard/api/service/user/UserService.java
  src/main/java/hanghaeboard/api/service/user/response/FindUser.java
  src/main/java/hanghaeboard/api/service/user/response/LoginResponse.java
  src/main/java/hanghaeboard/config/ClockConfig.java
  src/main/java/hanghaeboard/domain/member/MemberRepository.java
  src/main/java/hanghaeboard/domain/user/User.java
  src/main/java/hanghaeboard/domain/user/UserRepository.java
  src/main/java/hanghaeboard/util/JwtUtil.java
  src/main/resources/application.yml
  src/test/java/hanghaeboard/api/controller/user/UserControllerTest.java
  src/test/java/hanghaeboard/api/service/member/MemberServiceTest.java
  src/test/java/hanghaeboard/api/service/user/UserServiceTest.java
  src/test/java/hanghaeboard/domain/member/MemberRepositoryTest.java
  src/test/java/hanghaeboard/domain/user/UserRepositoryTest.java
Labels: ✨ Feature

#24 [PR - 2주차 이건엽] 회원가입, 로그인
  build.gradle
  src/main/generated/hanghaeboard/domain/member/QMember.java
  src/main/java/hanghaeboard/api/ApiResponse.java
  src/main/java/hanghaeboard/api/controller/user/UserController.java
  src/main/java/hanghaeboard/api/controller/user/request/CreateUserRequest.java
  src/main/java/hanghaeboard/api/controller/user/request/LoginRequest.java
  src/main/java/hanghaeboard/api/exception/ApiControllerAdvice.java
  src/main/java/hanghaeboard/api/service/member/MemberService.java
  src/main/java/hanghaeboard/api/service/member/response/FindMember.java
  src/main/java/hanghaeboard/api/service/user/UserService.java
  src/main/java/hanghaeboard/api/service/user/response/FindUser.java
  src/main/java/hanghaeboard/api/service/user/response/LoginResponse.java
  src/main/java/hanghaeboard/config/ClockConfig.java
  src/main/java/hanghaeboard/domain/member/MemberRepository.java
  src/main/java/hanghaeboard/domain/user/User.java
  src/main/java/hanghaeboard/domain/user/UserRepository.java
  src/main/java/hanghaeboard/util/JwtUtil.java
  src/main/resources/application.yml
  src/test/java/hanghaeboard/api/controller/user/UserControllerTest.java
  src/test/java/hanghaeboard/api/service/member/MemberServiceTest.java
  src/test/java/hanghaeboard/api/service/user/UserServiceTest.java
  src/test/java/hanghaeboard/domain/member/MemberRepositoryTest.java
  src/test/java/hanghaeboard/domain/user/UserRepositoryTest.java
Labels: ✨ Feature

#22 [PR - 2주차 박한영] 회원가입, 로그인 구현 및 AWS 배포
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.yml
  docs/ApiDocument.md
  docs/ERD.md
  docs/UseCase.md
  docs/WIL/week2.md
  src/main/java/prestudy/framework/spring/api/controller/user/UserController.java
  src/main/java/prestudy/framework/spring/api/controller/user/request/UserCreateRequest.java
  src/main/java/prestudy/framework/spring/api/controller/user/request/UserLoginRequest.java
  src/main/java/prestudy/framework/spring/api/jwt/JwtProvider.java
  src/main/java/prestudy/framework/spring/api/jwt/JwtResponseUtils.java
  src/main/java/prestudy/framework/spring/api/service/user/UserService.java
  src/main/java/prestudy/framework/spring/api/service/user/command/UserCreateCommand.java
  src/main/java/prestudy/framework/spring/api/service/user/command/UserLoginCommand.java
  src/main/java/prestudy/framework/spring/domain/user/User.java
  src/main/java/prestudy/framework/spring/domain/user/UserRepository.java
  src/main/resources/application.yml
  src/test/java/prestudy/framework/spring/api/controller/user/UserControllerTest.java
  src/test/java/prestudy/framework/spring/api/jwt/JwtProviderTest.java
  src/test/java/prestudy/framework/spring/api/service/user/UserServiceTest.java
  src/test/java/prestudy/framework/spring/domain/user/UserRepositoryTest.java
  src/test/java/prestudy/framework/spring/domain/user/UserTest.java
  src/test/java/prestudy/framework/spring/support/ControllerTestSupport.java
Labels: ✨ Feature, ⚙️ DevOps, 🧱 Infra

#20 [2주차 - 진문장] 회원가입 및 로그인 기능 구현
  .gitignore
  Dockerfile
  assignments/week2/Q&A.md
  build.gradle
  src/main/java/com/hhplus/precourse/common/component/JwtTokenManager.java
  src/main/java/com/hhplus/precourse/common/exception/CommonExceptionHandler.java
  src/main/java/com/hhplus/precourse/common/support/ApplicationStatus.java
  src/main/java/com/hhplus/precourse/post/controller/CreatePostController.java
  src/main/java/com/hhplus/precourse/post/controller/UpdatePostController.java
  src/main/java/com/hhplus/precourse/user/controller/CreateUserController.java
  src/main/java/com/hhplus/precourse/user/controller/LoginController.java
  src/main/java/com/hhplus/precourse/user/domain/User.java
  src/main/java/com/hhplus/precourse/user/repository/UserRepository.java
  src/main/java/com/hhplus/precourse/user/service/CreateUserService.java
  src/main/java/com/hhplus/precourse/user/service/LoginService.java
  src/main/resources/application.yml
  src/test/java/com/hhplus/precourse/common/ControllerTestContext.java
  src/test/java/com/hhplus/precourse/common/IntegrationTest.java
  src/test/java/com/hhplus/precourse/common/MySQLTestContainerConfig.java
  src/test/java/com/hhplus/precourse/common/component/JwtTokenManagerTest.java
  src/test/java/com/hhplus/precourse/integration/PostIntegrationTest.java
  src/test/java/com/hhplus/precourse/integration/UserIntegrationTest.java
  src/test/java/com/hhplus/precourse/user/controller/CreateUserControllerTest.java
  src/test/java/com/hhplus/precourse/user/controller/LoginControllerTest.java
  src/test/java/com/hhplus/precourse/user/domain/UserFixture.java
  src/test/java/com/hhplus/precourse/user/domain/UserTest.java
  src/test/java/com/hhplus/precourse/user/service/CreateUserServiceTest.java
  src/test/java/com/hhplus/precourse/user/service/LoginServiceTest.java
  src/test/resources/application-integration-test.yml
  src/test/resources/application-test.yml
Labels: ✨ Feature

#27 [PR - 3주차 박한영] 추가 요구사항 구현하기
  .github/workflows/deploy.yml
  docs/ApiDocument.md
  docs/ERD.md
  docs/UseCase.md
  src/main/java/prestudy/framework/spring/api/authenticate/Authentication.java
  src/main/java/prestudy/framework/spring/api/authenticate/AuthenticationHandler.java
  src/main/java/prestudy/framework/spring/api/config/WebConfig.java
  src/main/java/prestudy/framework/spring/api/controller/board/BoardController.java
  src/main/java/prestudy/framework/spring/api/controller/comment/CommentController.java
  src/main/java/prestudy/framework/spring/api/controller/comment/request/CommentCreateRequest.java
  src/main/java/prestudy/framework/spring/api/controller/comment/request/CommentUpdateRequest.java
  src/main/java/prestudy/framework/spring/api/controller/comment/response/CommentResponse.java
  src/main/java/prestudy/framework/spring/api/controller/user/UserController.java
  src/main/java/prestudy/framework/spring/api/exception/ApiExceptionHandler.java
  src/main/java/prestudy/framework/spring/api/jwt/JwtInterceptor.java
  src/main/java/prestudy/framework/spring/api/jwt/JwtProvider.java
  src/main/java/prestudy/framework/spring/api/jwt/JwtRequestUtils.java
  src/main/java/prestudy/framework/spring/api/service/comment/CommentService.java
  src/main/java/prestudy/framework/spring/api/service/comment/command/CommentCreateCommand.java
  src/main/java/prestudy/framework/spring/api/service/comment/command/CommentDeleteCommand.java
  src/main/java/prestudy/framework/spring/api/service/comment/command/CommentUpdateCommand.java
  src/main/java/prestudy/framework/spring/api/service/user/UserService.java
  src/main/java/prestudy/framework/spring/api/service/user/command/UserCreateCommand.java
  src/main/java/prestudy/framework/spring/domain/board/Board.java
  src/main/java/prestudy/framework/spring/domain/comment/Comment.java
  src/main/java/prestudy/framework/spring/domain/comment/CommentRepository.java
  src/main/java/prestudy/framework/spring/domain/user/User.java
  src/main/java/prestudy/framework/spring/domain/user/UserRole.java
  src/test/java/prestudy/framework/spring/api/authenticate/AuthenticationHandlerTest.java
  src/test/java/prestudy/framework/spring/api/controller/board/BoardControllerTest.java
  src/test/java/prestudy/framework/spring/api/controller/comment/CommentControllerTest.java
  src/test/java/prestudy/framework/spring/api/controller/user/UserControllerTest.java
  src/test/java/prestudy/framework/spring/api/jwt/JwtInterceptorTest.java
  src/test/java/prestudy/framework/spring/api/jwt/JwtProviderTest.java
  src/test/java/prestudy/framework/spring/api/jwt/JwtRequestUtilsTest.java
  src/test/java/prestudy/framework/spring/api/service/comment/CommentServiceTest.java
  src/test/java/prestudy/framework/spring/api/service/user/UserServiceTest.java
  src/test/java/prestudy/framework/spring/domain/comment/CommentTest.java
  src/test/java/prestudy/framework/spring/domain/user/UserRepositoryTest.java
  src/test/java/prestudy/framework/spring/domain/user/UserTest.java
  src/test/java/prestudy/framework/spring/support/ControllerTestSupport.java
Labels: ✨ Feature

#34 [PR - 4주차 진문장] 추가 요구사항에 의한 변경사항 적용
  src/main/java/com/hhplus/precourse/comment/repository/CommentRepository.java
  src/main/java/com/hhplus/precourse/common/web/CommonObjectMapper.java
  src/main/java/com/hhplus/precourse/post/controller/GetPostController.java
  src/main/java/com/hhplus/precourse/post/controller/GetPostListController.java
  src/main/java/com/hhplus/precourse/post/service/GetPostListService.java
  src/main/java/com/hhplus/precourse/post/service/GetPostService.java
  src/main/java/com/hhplus/precourse/post/vo/PostCommentVo.java
  src/main/java/com/hhplus/precourse/post/vo/PostDetails.java
  src/main/java/com/hhplus/precourse/post/vo/PostSummary.java
  src/test/java/com/hhplus/precourse/integration/PostIntegrationTest.java
  src/test/java/com/hhplus/precourse/post/controller/GetPostControllerTest.java
  src/test/java/com/hhplus/precourse/post/controller/GetPostListControllerTest.java
Labels: ✨ Feature
